/**
 * This file was generated by the JPA Modeler
 */
package vo;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

/**
 * @author Eduardo
 */
@Entity
public class Entrada implements Serializable {

    @Id
    private Long id_entrada;

    @Basic
    private int numero_nf;

    @Basic
    private Date dt_entrada;

    @Basic
    private Integer valor_total;

    @ManyToMany(targetEntity = Material.class, mappedBy = "id_entrada")
    private List<Material> id_material;

    public Long getId_entrada() {
        return this.id_entrada;
    }

    public void setId_entrada(Long id_entrada) {
        this.id_entrada = id_entrada;
    }

    public int getNumero_nf() {
        return this.numero_nf;
    }

    public void setNumero_nf(int numero_nf) {
        this.numero_nf = numero_nf;
    }

    public Date getDt_entrada() {
        return this.dt_entrada;
    }

    public void setDt_entrada(Date dt_entrada) {
        this.dt_entrada = dt_entrada;
    }

    public Integer getValor_total() {
        return this.valor_total;
    }

    public void setValor_total(Integer valor_total) {
        this.valor_total = valor_total;
    }

    public List<Material> getId_material() {
        return this.id_material;
    }

    public void setId_material(List<Material> id_material) {
        this.id_material = id_material;
    }

}
