/**
 * This file was generated by the JPA Modeler
 */
package vo;

import DAO.EntidadeBase;
import java.io.Serializable;
import java.sql.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

/**
 * @author Eduardo
 */
@Entity
public class Entrada implements Serializable, EntidadeBase {

    @Id
    private Long id_entrada;

    @Basic
    private int numero_nf;

    @Basic
    private Date dt_entrada;

    @Basic
    private Integer valor_total;

    @ManyToOne(fetch = FetchType.EAGER)
    private Fornecedor id_fornecedor = null;

    @Override
    public Long getId() {
        return this.id_entrada;
    }

    public void setId_entrada(Long id_entrada) {
        this.id_entrada = id_entrada;
    }

    public int getNumero_nf() {
        return this.numero_nf;
    }

    public void setNumero_nf(int numero_nf) {
        this.numero_nf = numero_nf;
    }

    public Date getDt_entrada() {
        return this.dt_entrada;
    }

    public void setDt_entrada(Date dt_entrada) {
        this.dt_entrada = dt_entrada;
    }

    public Integer getValor_total() {
        return this.valor_total;
    }

    public void setValor_total(Integer valor_total) {
        this.valor_total = valor_total;
    }

    public Fornecedor getId_fornecedor() {
        return id_fornecedor;
    }

    public void setId_fornecedor(Fornecedor id_fornecedor) {
        this.id_fornecedor = id_fornecedor;
    }

  
}
