/**
 * This file was generated by the JPA Modeler
 */
package vo;

import DAO.EntidadeBase;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;

/**
 * @author Eduardo
 */
@Entity
public class Material implements Serializable, EntidadeBase {

    @Id
    private Long id_material;

    @Basic
    private String quantidade;

    @Basic
    private String descricao;

    @ManyToOne(fetch = FetchType.EAGER)
    private TipoUnidade id_tipo_unidade = null;

    @ManyToOne(fetch = FetchType.EAGER)
    private Categoria id_categoria = null;

    
    public TipoUnidade getId_tipo_unidade() {
        return id_tipo_unidade;
    }

    public void setId_tipo_unidade(TipoUnidade id_tipo_unidade) {
        this.id_tipo_unidade = id_tipo_unidade;
    }

    public Categoria getId_categoria() {
        return id_categoria;
    }

    public void setId_categoria(Categoria id_categoria) {
        this.id_categoria = id_categoria;
    }

  

    @Override
    public Long getId() {
        return this.id_material;
    }

    public void setId_material(Long id_material) {
        this.id_material = id_material;
    }

    public String getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

 

}
