/**
 * This file was generated by the JPA Modeler
 */
package vo;

import DAO.EntidadeBase;
import java.io.Serializable;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;

/**
 * @author Eduardo
 */
@Entity
public class Material implements Serializable, EntidadeBase {

    @Id
    private Long id_material;

    @Basic
    private String quantidade;

    @Basic
    private String descricao;

    @ManyToMany(targetEntity = Entrada.class)
    @JoinTable(name = "teste2", schema = "teste")
    private List<Entrada> id_entrada;

    @Override
    public Long getId() {
        return this.id_material;
    }

    public void setId_material(Long id_material) {
        this.id_material = id_material;
    }

    public String getQuantidade() {
        return this.quantidade;
    }

    public void setQuantidade(String quantidade) {
        this.quantidade = quantidade;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Entrada> getId_entrada() {
        return this.id_entrada;
    }

    public void setId_entrada(List<Entrada> id_entrada) {
        this.id_entrada = id_entrada;
    }

}
